/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as UniverseRouteImport } from './routes/universe'
import { Route as StoryCardPreviewRouteImport } from './routes/story-card-preview'
import { Route as SceneRouteImport } from './routes/scene'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PlayEndingRouteImport } from './routes/play-ending'
import { Route as PlayRouteImport } from './routes/play'
import { Route as Minigame2RouteImport } from './routes/minigame2'
import { Route as MinigameRouteImport } from './routes/minigame'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MatchingRouteImport } from './routes/matching'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as HubRouteImport } from './routes/hub'
import { Route as HuatangchunRouteImport } from './routes/huatangchun'
import { Route as EndingRouteImport } from './routes/ending'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as AdaptPreviewRouteImport } from './routes/adapt-preview'
import { Route as AdaptRouteImport } from './routes/adapt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharacterIdRouteImport } from './routes/character.$id'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const UniverseRoute = UniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryCardPreviewRoute = StoryCardPreviewRouteImport.update({
  id: '/story-card-preview',
  path: '/story-card-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SceneRoute = SceneRouteImport.update({
  id: '/scene',
  path: '/scene',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayEndingRoute = PlayEndingRouteImport.update({
  id: '/play-ending',
  path: '/play-ending',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const Minigame2Route = Minigame2RouteImport.update({
  id: '/minigame2',
  path: '/minigame2',
  getParentRoute: () => rootRouteImport,
} as any)
const MinigameRoute = MinigameRouteImport.update({
  id: '/minigame',
  path: '/minigame',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRoute = MatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const HuatangchunRoute = HuatangchunRouteImport.update({
  id: '/huatangchun',
  path: '/huatangchun',
  getParentRoute: () => rootRouteImport,
} as any)
const EndingRoute = EndingRouteImport.update({
  id: '/ending',
  path: '/ending',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptPreviewRoute = AdaptPreviewRouteImport.update({
  id: '/adapt-preview',
  path: '/adapt-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptRoute = AdaptRouteImport.update({
  id: '/adapt',
  path: '/adapt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterIdRoute = CharacterIdRouteImport.update({
  id: '/character/$id',
  path: '/character/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adapt': typeof AdaptRoute
  '/adapt-preview': typeof AdaptPreviewRoute
  '/confirm': typeof ConfirmRoute
  '/ending': typeof EndingRoute
  '/huatangchun': typeof HuatangchunRoute
  '/hub': typeof HubRoute
  '/invite': typeof InviteRoute
  '/lobby': typeof LobbyRoute
  '/matching': typeof MatchingRoute
  '/mcp': typeof McpRoute
  '/minigame': typeof MinigameRoute
  '/minigame2': typeof Minigame2Route
  '/play': typeof PlayRoute
  '/play-ending': typeof PlayEndingRoute
  '/report': typeof ReportRoute
  '/scene': typeof SceneRoute
  '/story-card-preview': typeof StoryCardPreviewRoute
  '/universe': typeof UniverseRoute
  '/workshop': typeof WorkshopRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/character/$id': typeof CharacterIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adapt': typeof AdaptRoute
  '/adapt-preview': typeof AdaptPreviewRoute
  '/confirm': typeof ConfirmRoute
  '/ending': typeof EndingRoute
  '/huatangchun': typeof HuatangchunRoute
  '/hub': typeof HubRoute
  '/invite': typeof InviteRoute
  '/lobby': typeof LobbyRoute
  '/matching': typeof MatchingRoute
  '/mcp': typeof McpRoute
  '/minigame': typeof MinigameRoute
  '/minigame2': typeof Minigame2Route
  '/play': typeof PlayRoute
  '/play-ending': typeof PlayEndingRoute
  '/report': typeof ReportRoute
  '/scene': typeof SceneRoute
  '/story-card-preview': typeof StoryCardPreviewRoute
  '/universe': typeof UniverseRoute
  '/workshop': typeof WorkshopRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/character/$id': typeof CharacterIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adapt': typeof AdaptRoute
  '/adapt-preview': typeof AdaptPreviewRoute
  '/confirm': typeof ConfirmRoute
  '/ending': typeof EndingRoute
  '/huatangchun': typeof HuatangchunRoute
  '/hub': typeof HubRoute
  '/invite': typeof InviteRoute
  '/lobby': typeof LobbyRoute
  '/matching': typeof MatchingRoute
  '/mcp': typeof McpRoute
  '/minigame': typeof MinigameRoute
  '/minigame2': typeof Minigame2Route
  '/play': typeof PlayRoute
  '/play-ending': typeof PlayEndingRoute
  '/report': typeof ReportRoute
  '/scene': typeof SceneRoute
  '/story-card-preview': typeof StoryCardPreviewRoute
  '/universe': typeof UniverseRoute
  '/workshop': typeof WorkshopRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/character/$id': typeof CharacterIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adapt'
    | '/adapt-preview'
    | '/confirm'
    | '/ending'
    | '/huatangchun'
    | '/hub'
    | '/invite'
    | '/lobby'
    | '/matching'
    | '/mcp'
    | '/minigame'
    | '/minigame2'
    | '/play'
    | '/play-ending'
    | '/report'
    | '/scene'
    | '/story-card-preview'
    | '/universe'
    | '/workshop'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/character/$id'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adapt'
    | '/adapt-preview'
    | '/confirm'
    | '/ending'
    | '/huatangchun'
    | '/hub'
    | '/invite'
    | '/lobby'
    | '/matching'
    | '/mcp'
    | '/minigame'
    | '/minigame2'
    | '/play'
    | '/play-ending'
    | '/report'
    | '/scene'
    | '/story-card-preview'
    | '/universe'
    | '/workshop'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/character/$id'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/adapt'
    | '/adapt-preview'
    | '/confirm'
    | '/ending'
    | '/huatangchun'
    | '/hub'
    | '/invite'
    | '/lobby'
    | '/matching'
    | '/mcp'
    | '/minigame'
    | '/minigame2'
    | '/play'
    | '/play-ending'
    | '/report'
    | '/scene'
    | '/story-card-preview'
    | '/universe'
    | '/workshop'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/character/$id'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdaptRoute: typeof AdaptRoute
  AdaptPreviewRoute: typeof AdaptPreviewRoute
  ConfirmRoute: typeof ConfirmRoute
  EndingRoute: typeof EndingRoute
  HuatangchunRoute: typeof HuatangchunRoute
  HubRoute: typeof HubRoute
  InviteRoute: typeof InviteRoute
  LobbyRoute: typeof LobbyRoute
  MatchingRoute: typeof MatchingRoute
  McpRoute: typeof McpRoute
  MinigameRoute: typeof MinigameRoute
  Minigame2Route: typeof Minigame2Route
  PlayRoute: typeof PlayRoute
  PlayEndingRoute: typeof PlayEndingRoute
  ReportRoute: typeof ReportRoute
  SceneRoute: typeof SceneRoute
  StoryCardPreviewRoute: typeof StoryCardPreviewRoute
  UniverseRoute: typeof UniverseRoute
  WorkshopRoute: typeof WorkshopRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CharacterIdRoute: typeof CharacterIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universe': {
      id: '/universe'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof UniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-card-preview': {
      id: '/story-card-preview'
      path: '/story-card-preview'
      fullPath: '/story-card-preview'
      preLoaderRoute: typeof StoryCardPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene': {
      id: '/scene'
      path: '/scene'
      fullPath: '/scene'
      preLoaderRoute: typeof SceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play-ending': {
      id: '/play-ending'
      path: '/play-ending'
      fullPath: '/play-ending'
      preLoaderRoute: typeof PlayEndingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minigame2': {
      id: '/minigame2'
      path: '/minigame2'
      fullPath: '/minigame2'
      preLoaderRoute: typeof Minigame2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minigame': {
      id: '/minigame'
      path: '/minigame'
      fullPath: '/minigame'
      preLoaderRoute: typeof MinigameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huatangchun': {
      id: '/huatangchun'
      path: '/huatangchun'
      fullPath: '/huatangchun'
      preLoaderRoute: typeof HuatangchunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ending': {
      id: '/ending'
      path: '/ending'
      fullPath: '/ending'
      preLoaderRoute: typeof EndingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adapt-preview': {
      id: '/adapt-preview'
      path: '/adapt-preview'
      fullPath: '/adapt-preview'
      preLoaderRoute: typeof AdaptPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adapt': {
      id: '/adapt'
      path: '/adapt'
      fullPath: '/adapt'
      preLoaderRoute: typeof AdaptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/$id': {
      id: '/character/$id'
      path: '/character/$id'
      fullPath: '/character/$id'
      preLoaderRoute: typeof CharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaptRoute: AdaptRoute,
  AdaptPreviewRoute: AdaptPreviewRoute,
  ConfirmRoute: ConfirmRoute,
  EndingRoute: EndingRoute,
  HuatangchunRoute: HuatangchunRoute,
  HubRoute: HubRoute,
  InviteRoute: InviteRoute,
  LobbyRoute: LobbyRoute,
  MatchingRoute: MatchingRoute,
  McpRoute: McpRoute,
  MinigameRoute: MinigameRoute,
  Minigame2Route: Minigame2Route,
  PlayRoute: PlayRoute,
  PlayEndingRoute: PlayEndingRoute,
  ReportRoute: ReportRoute,
  SceneRoute: SceneRoute,
  StoryCardPreviewRoute: StoryCardPreviewRoute,
  UniverseRoute: UniverseRoute,
  WorkshopRoute: WorkshopRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CharacterIdRoute: CharacterIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
