/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SceneRouteImport } from './routes/scene'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PlayEndingRouteImport } from './routes/play-ending'
import { Route as PlayRouteImport } from './routes/play'
import { Route as NovelRouteImport } from './routes/novel'
import { Route as MatchingRouteImport } from './routes/matching'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as HuatangchunRouteImport } from './routes/huatangchun'
import { Route as EndingRouteImport } from './routes/ending'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as AdaptPreviewRouteImport } from './routes/adapt-preview'
import { Route as AdaptRouteImport } from './routes/adapt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharacterIdRouteImport } from './routes/character.$id'

const SceneRoute = SceneRouteImport.update({
  id: '/scene',
  path: '/scene',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayEndingRoute = PlayEndingRouteImport.update({
  id: '/play-ending',
  path: '/play-ending',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelRoute = NovelRouteImport.update({
  id: '/novel',
  path: '/novel',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRoute = MatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const HuatangchunRoute = HuatangchunRouteImport.update({
  id: '/huatangchun',
  path: '/huatangchun',
  getParentRoute: () => rootRouteImport,
} as any)
const EndingRoute = EndingRouteImport.update({
  id: '/ending',
  path: '/ending',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptPreviewRoute = AdaptPreviewRouteImport.update({
  id: '/adapt-preview',
  path: '/adapt-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptRoute = AdaptRouteImport.update({
  id: '/adapt',
  path: '/adapt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterIdRoute = CharacterIdRouteImport.update({
  id: '/character/$id',
  path: '/character/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adapt': typeof AdaptRoute
  '/adapt-preview': typeof AdaptPreviewRoute
  '/confirm': typeof ConfirmRoute
  '/ending': typeof EndingRoute
  '/huatangchun': typeof HuatangchunRoute
  '/invite': typeof InviteRoute
  '/lobby': typeof LobbyRoute
  '/matching': typeof MatchingRoute
  '/novel': typeof NovelRoute
  '/play': typeof PlayRoute
  '/play-ending': typeof PlayEndingRoute
  '/report': typeof ReportRoute
  '/scene': typeof SceneRoute
  '/character/$id': typeof CharacterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adapt': typeof AdaptRoute
  '/adapt-preview': typeof AdaptPreviewRoute
  '/confirm': typeof ConfirmRoute
  '/ending': typeof EndingRoute
  '/huatangchun': typeof HuatangchunRoute
  '/invite': typeof InviteRoute
  '/lobby': typeof LobbyRoute
  '/matching': typeof MatchingRoute
  '/novel': typeof NovelRoute
  '/play': typeof PlayRoute
  '/play-ending': typeof PlayEndingRoute
  '/report': typeof ReportRoute
  '/scene': typeof SceneRoute
  '/character/$id': typeof CharacterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adapt': typeof AdaptRoute
  '/adapt-preview': typeof AdaptPreviewRoute
  '/confirm': typeof ConfirmRoute
  '/ending': typeof EndingRoute
  '/huatangchun': typeof HuatangchunRoute
  '/invite': typeof InviteRoute
  '/lobby': typeof LobbyRoute
  '/matching': typeof MatchingRoute
  '/novel': typeof NovelRoute
  '/play': typeof PlayRoute
  '/play-ending': typeof PlayEndingRoute
  '/report': typeof ReportRoute
  '/scene': typeof SceneRoute
  '/character/$id': typeof CharacterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adapt'
    | '/adapt-preview'
    | '/confirm'
    | '/ending'
    | '/huatangchun'
    | '/invite'
    | '/lobby'
    | '/matching'
    | '/novel'
    | '/play'
    | '/play-ending'
    | '/report'
    | '/scene'
    | '/character/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adapt'
    | '/adapt-preview'
    | '/confirm'
    | '/ending'
    | '/huatangchun'
    | '/invite'
    | '/lobby'
    | '/matching'
    | '/novel'
    | '/play'
    | '/play-ending'
    | '/report'
    | '/scene'
    | '/character/$id'
  id:
    | '__root__'
    | '/'
    | '/adapt'
    | '/adapt-preview'
    | '/confirm'
    | '/ending'
    | '/huatangchun'
    | '/invite'
    | '/lobby'
    | '/matching'
    | '/novel'
    | '/play'
    | '/play-ending'
    | '/report'
    | '/scene'
    | '/character/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdaptRoute: typeof AdaptRoute
  AdaptPreviewRoute: typeof AdaptPreviewRoute
  ConfirmRoute: typeof ConfirmRoute
  EndingRoute: typeof EndingRoute
  HuatangchunRoute: typeof HuatangchunRoute
  InviteRoute: typeof InviteRoute
  LobbyRoute: typeof LobbyRoute
  MatchingRoute: typeof MatchingRoute
  NovelRoute: typeof NovelRoute
  PlayRoute: typeof PlayRoute
  PlayEndingRoute: typeof PlayEndingRoute
  ReportRoute: typeof ReportRoute
  SceneRoute: typeof SceneRoute
  CharacterIdRoute: typeof CharacterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scene': {
      id: '/scene'
      path: '/scene'
      fullPath: '/scene'
      preLoaderRoute: typeof SceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play-ending': {
      id: '/play-ending'
      path: '/play-ending'
      fullPath: '/play-ending'
      preLoaderRoute: typeof PlayEndingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novel': {
      id: '/novel'
      path: '/novel'
      fullPath: '/novel'
      preLoaderRoute: typeof NovelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huatangchun': {
      id: '/huatangchun'
      path: '/huatangchun'
      fullPath: '/huatangchun'
      preLoaderRoute: typeof HuatangchunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ending': {
      id: '/ending'
      path: '/ending'
      fullPath: '/ending'
      preLoaderRoute: typeof EndingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adapt-preview': {
      id: '/adapt-preview'
      path: '/adapt-preview'
      fullPath: '/adapt-preview'
      preLoaderRoute: typeof AdaptPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adapt': {
      id: '/adapt'
      path: '/adapt'
      fullPath: '/adapt'
      preLoaderRoute: typeof AdaptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/$id': {
      id: '/character/$id'
      path: '/character/$id'
      fullPath: '/character/$id'
      preLoaderRoute: typeof CharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaptRoute: AdaptRoute,
  AdaptPreviewRoute: AdaptPreviewRoute,
  ConfirmRoute: ConfirmRoute,
  EndingRoute: EndingRoute,
  HuatangchunRoute: HuatangchunRoute,
  InviteRoute: InviteRoute,
  LobbyRoute: LobbyRoute,
  MatchingRoute: MatchingRoute,
  NovelRoute: NovelRoute,
  PlayRoute: PlayRoute,
  PlayEndingRoute: PlayEndingRoute,
  ReportRoute: ReportRoute,
  SceneRoute: SceneRoute,
  CharacterIdRoute: CharacterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
